# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *

import list_of_post as list
import time

class Worker(QRunnable):
    '''
    Worker thread

    Inherits from QRunnable to handler worker thread setup, signals and wrap-up.

    :param callback: The function callback to run on this worker thread. Supplied args and
                     kwargs will be passed through to the runner.
    :type callback: function
    :param args: Arguments to pass to the callback function
    :param kwargs: Keywords to pass to the callback function

    '''

    def __init__(self, fn, *args, **kwargs):
        super(Worker, self).__init__()
        # Store constructor arguments (re-used for processing)
        self.fn = fn
        self.args = args
        self.kwargs = kwargs

    def run(self):
        '''
        Initialise the runner function with passed args, kwargs.
        '''
        self.fn(*self.args, **self.kwargs)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 10, 10, 10)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_main = QtWidgets.QLabel(self.centralwidget)
        self.title_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_main.setAutoFillBackground(True)
        self.title_main.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.title_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_main.setFrameShadow(QtWidgets.QFrame.Plain)
        self.title_main.setLineWidth(1)
        self.title_main.setTextFormat(QtCore.Qt.AutoText)
        self.title_main.setScaledContents(False)
        self.title_main.setAlignment(QtCore.Qt.AlignCenter)
        self.title_main.setWordWrap(True)
        self.title_main.setIndent(0)
        self.title_main.setObjectName("title_main")
        self.horizontalLayout.addWidget(self.title_main)
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout.addWidget(self.line_21)
        self.author_main = QtWidgets.QLabel(self.centralwidget)
        self.author_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.author_main.setAutoFillBackground(True)
        self.author_main.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.author_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.author_main.setLineWidth(1)
        self.author_main.setTextFormat(QtCore.Qt.AutoText)
        self.author_main.setScaledContents(True)
        self.author_main.setAlignment(QtCore.Qt.AlignCenter)
        self.author_main.setWordWrap(True)
        self.author_main.setIndent(0)
        self.author_main.setObjectName("author_main")
        self.horizontalLayout.addWidget(self.author_main)
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.horizontalLayout.addWidget(self.line_22)
        self.hour_main = QtWidgets.QLabel(self.centralwidget)
        self.hour_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour_main.setAutoFillBackground(True)
        self.hour_main.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.hour_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.hour_main.setLineWidth(1)
        self.hour_main.setTextFormat(QtCore.Qt.AutoText)
        self.hour_main.setScaledContents(True)
        self.hour_main.setAlignment(QtCore.Qt.AlignCenter)
        self.hour_main.setWordWrap(True)
        self.hour_main.setIndent(0)
        self.hour_main.setObjectName("hour_main")
        self.horizontalLayout.addWidget(self.hour_main)
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout.addWidget(self.line_23)
        self.views_main = QtWidgets.QLabel(self.centralwidget)
        self.views_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.views_main.setAutoFillBackground(True)
        self.views_main.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.views_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.views_main.setLineWidth(1)
        self.views_main.setTextFormat(QtCore.Qt.AutoText)
        self.views_main.setScaledContents(True)
        self.views_main.setAlignment(QtCore.Qt.AlignCenter)
        self.views_main.setWordWrap(True)
        self.views_main.setIndent(0)
        self.views_main.setObjectName("views_main")
        self.horizontalLayout.addWidget(self.views_main)
        self.line_24 = QtWidgets.QFrame(self.centralwidget)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.horizontalLayout.addWidget(self.line_24)
        self.answers_main = QtWidgets.QLabel(self.centralwidget)
        self.answers_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.answers_main.setAutoFillBackground(True)
        self.answers_main.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.answers_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answers_main.setLineWidth(1)
        self.answers_main.setTextFormat(QtCore.Qt.AutoText)
        self.answers_main.setScaledContents(True)
        self.answers_main.setAlignment(QtCore.Qt.AlignCenter)
        self.answers_main.setWordWrap(True)
        self.answers_main.setIndent(0)
        self.answers_main.setObjectName("answers_main")
        self.horizontalLayout.addWidget(self.answers_main)
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout.addWidget(self.line_25)
        self.describtion_main = QtWidgets.QLabel(self.centralwidget)
        self.describtion_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.describtion_main.setAutoFillBackground(True)
        self.describtion_main.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.describtion_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.describtion_main.setLineWidth(1)
        self.describtion_main.setTextFormat(QtCore.Qt.AutoText)
        self.describtion_main.setScaledContents(True)
        self.describtion_main.setAlignment(QtCore.Qt.AlignCenter)
        self.describtion_main.setWordWrap(True)
        self.describtion_main.setIndent(0)
        self.describtion_main.setObjectName("describtion_main")
        self.horizontalLayout.addWidget(self.describtion_main)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.last_update = QtWidgets.QLabel(self.centralwidget)
        self.last_update.setObjectName("last_update")
        self.gridLayout.addWidget(self.last_update, 4, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1033, 772))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_2.addWidget(self.line_19, 38, 0, 1, 6)
        self.describtion_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_4.setObjectName("describtion_4")
        self.gridLayout_2.addWidget(self.describtion_4, 7, 5, 1, 1)
        self.title_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_7.setScaledContents(True)
        self.title_7.setWordWrap(True)
        self.title_7.setObjectName("title_7")
        self.gridLayout_2.addWidget(self.title_7, 13, 0, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_2.addWidget(self.line_15, 30, 0, 1, 6)
        self.describtion_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_9.setObjectName("describtion_9")
        self.gridLayout_2.addWidget(self.describtion_9, 17, 5, 1, 1)
        self.title_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_5.setScaledContents(True)
        self.title_5.setWordWrap(True)
        self.title_5.setObjectName("title_5")
        self.gridLayout_2.addWidget(self.title_5, 9, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 10, 0, 1, 6)
        self.author_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_14.setWordWrap(True)
        self.author_14.setObjectName("author_14")
        self.gridLayout_2.addWidget(self.author_14, 27, 1, 1, 1)
        self.author_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_19.setWordWrap(True)
        self.author_19.setObjectName("author_19")
        self.gridLayout_2.addWidget(self.author_19, 37, 1, 1, 1)
        self.title_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_18.setScaledContents(True)
        self.title_18.setWordWrap(True)
        self.title_18.setObjectName("title_18")
        self.gridLayout_2.addWidget(self.title_18, 35, 0, 1, 1)
        self.describtion_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_12.setObjectName("describtion_12")
        self.gridLayout_2.addWidget(self.describtion_12, 23, 5, 1, 1)
        self.answers_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_9.setEnabled(True)
        self.answers_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_9.setTextFormat(QtCore.Qt.AutoText)
        self.answers_9.setScaledContents(True)
        self.answers_9.setObjectName("answers_9")
        self.gridLayout_2.addWidget(self.answers_9, 17, 4, 1, 1)
        self.describtion_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_14.setObjectName("describtion_14")
        self.gridLayout_2.addWidget(self.describtion_14, 27, 5, 1, 1)
        self.title_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_13.setScaledContents(True)
        self.title_13.setWordWrap(True)
        self.title_13.setObjectName("title_13")
        self.gridLayout_2.addWidget(self.title_13, 25, 0, 1, 1)
        self.author_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_3.setWordWrap(True)
        self.author_3.setObjectName("author_3")
        self.gridLayout_2.addWidget(self.author_3, 5, 1, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_2.addWidget(self.line_16, 32, 0, 1, 6)
        self.hour_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_7.setScaledContents(True)
        self.hour_7.setWordWrap(True)
        self.hour_7.setObjectName("hour_7")
        self.gridLayout_2.addWidget(self.hour_7, 13, 2, 1, 1)
        self.answers_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_18.setEnabled(True)
        self.answers_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_18.setTextFormat(QtCore.Qt.AutoText)
        self.answers_18.setScaledContents(True)
        self.answers_18.setObjectName("answers_18")
        self.gridLayout_2.addWidget(self.answers_18, 35, 4, 1, 1)
        self.hour_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_2.setScaledContents(True)
        self.hour_2.setWordWrap(True)
        self.hour_2.setObjectName("hour_2")
        self.gridLayout_2.addWidget(self.hour_2, 3, 2, 1, 1)
        self.title_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_4.setScaledContents(True)
        self.title_4.setWordWrap(True)
        self.title_4.setObjectName("title_4")
        self.gridLayout_2.addWidget(self.title_4, 7, 0, 1, 1)
        self.hour_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_6.setScaledContents(True)
        self.hour_6.setWordWrap(True)
        self.hour_6.setObjectName("hour_6")
        self.gridLayout_2.addWidget(self.hour_6, 11, 2, 1, 1)
        self.describtion_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_2.setObjectName("describtion_2")
        self.gridLayout_2.addWidget(self.describtion_2, 3, 5, 1, 1)
        self.views_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_13.setScaledContents(True)
        self.views_13.setWordWrap(True)
        self.views_13.setObjectName("views_13")
        self.gridLayout_2.addWidget(self.views_13, 25, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setEnabled(True)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 4, 0, 1, 6)
        self.author_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_11.setWordWrap(True)
        self.author_11.setObjectName("author_11")
        self.gridLayout_2.addWidget(self.author_11, 21, 1, 1, 1)
        self.views_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_20.setScaledContents(True)
        self.views_20.setWordWrap(True)
        self.views_20.setObjectName("views_20")
        self.gridLayout_2.addWidget(self.views_20, 39, 3, 1, 1)
        self.views_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_17.setScaledContents(True)
        self.views_17.setWordWrap(True)
        self.views_17.setObjectName("views_17")
        self.gridLayout_2.addWidget(self.views_17, 33, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 8, 0, 1, 6)
        self.line_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_2.addWidget(self.line_18, 36, 0, 1, 6)
        self.title_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_6.setScaledContents(True)
        self.title_6.setWordWrap(True)
        self.title_6.setObjectName("title_6")
        self.gridLayout_2.addWidget(self.title_6, 11, 0, 1, 1)
        self.hour_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_4.setScaledContents(True)
        self.hour_4.setWordWrap(True)
        self.hour_4.setObjectName("hour_4")
        self.gridLayout_2.addWidget(self.hour_4, 7, 2, 1, 1)
        self.author_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_20.setWordWrap(True)
        self.author_20.setObjectName("author_20")
        self.gridLayout_2.addWidget(self.author_20, 39, 1, 1, 1)
        self.author_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_9.setWordWrap(True)
        self.author_9.setObjectName("author_9")
        self.gridLayout_2.addWidget(self.author_9, 17, 1, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_2.addWidget(self.line_17, 34, 0, 1, 6)
        self.views_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_14.setScaledContents(True)
        self.views_14.setWordWrap(True)
        self.views_14.setObjectName("views_14")
        self.gridLayout_2.addWidget(self.views_14, 27, 3, 1, 1)
        self.describtion_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_16.setObjectName("describtion_16")
        self.gridLayout_2.addWidget(self.describtion_16, 31, 5, 1, 1)
        self.author_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_16.setWordWrap(True)
        self.author_16.setObjectName("author_16")
        self.gridLayout_2.addWidget(self.author_16, 31, 1, 1, 1)
        self.hour_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_17.setScaledContents(True)
        self.hour_17.setWordWrap(True)
        self.hour_17.setObjectName("hour_17")
        self.gridLayout_2.addWidget(self.hour_17, 33, 2, 1, 1)
        self.answers_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_8.setEnabled(True)
        self.answers_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_8.setTextFormat(QtCore.Qt.AutoText)
        self.answers_8.setScaledContents(True)
        self.answers_8.setObjectName("answers_8")
        self.gridLayout_2.addWidget(self.answers_8, 15, 4, 1, 1)
        self.author_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_1.setWordWrap(True)
        self.author_1.setObjectName("author_1")
        self.gridLayout_2.addWidget(self.author_1, 1, 1, 1, 1)
        self.views_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_8.setScaledContents(True)
        self.views_8.setWordWrap(True)
        self.views_8.setObjectName("views_8")
        self.gridLayout_2.addWidget(self.views_8, 15, 3, 1, 1)
        self.author_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_10.setWordWrap(True)
        self.author_10.setObjectName("author_10")
        self.gridLayout_2.addWidget(self.author_10, 19, 1, 1, 1)
        self.describtion_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_11.setObjectName("describtion_11")
        self.gridLayout_2.addWidget(self.describtion_11, 21, 5, 1, 1)
        self.describtion_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_19.setObjectName("describtion_19")
        self.gridLayout_2.addWidget(self.describtion_19, 37, 5, 1, 1)
        self.hour_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_13.setScaledContents(True)
        self.hour_13.setWordWrap(True)
        self.hour_13.setObjectName("hour_13")
        self.gridLayout_2.addWidget(self.hour_13, 25, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 26, 0, 1, 6)
        self.author_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_18.setWordWrap(True)
        self.author_18.setObjectName("author_18")
        self.gridLayout_2.addWidget(self.author_18, 35, 1, 1, 1)
        self.title_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_11.setScaledContents(True)
        self.title_11.setWordWrap(True)
        self.title_11.setObjectName("title_11")
        self.gridLayout_2.addWidget(self.title_11, 21, 0, 1, 1)
        self.views_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_2.setScaledContents(True)
        self.views_2.setWordWrap(True)
        self.views_2.setObjectName("views_2")
        self.gridLayout_2.addWidget(self.views_2, 3, 3, 1, 1)
        self.hour_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_11.setScaledContents(True)
        self.hour_11.setWordWrap(True)
        self.hour_11.setObjectName("hour_11")
        self.gridLayout_2.addWidget(self.hour_11, 21, 2, 1, 1)
        self.views_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_3.setScaledContents(True)
        self.views_3.setWordWrap(True)
        self.views_3.setObjectName("views_3")
        self.gridLayout_2.addWidget(self.views_3, 5, 3, 1, 1)
        self.author_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_15.setWordWrap(True)
        self.author_15.setObjectName("author_15")
        self.gridLayout_2.addWidget(self.author_15, 29, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 16, 0, 1, 6)
        self.describtion_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_8.setObjectName("describtion_8")
        self.gridLayout_2.addWidget(self.describtion_8, 15, 5, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 20, 0, 1, 6)
        self.answers_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_13.setEnabled(True)
        self.answers_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_13.setTextFormat(QtCore.Qt.AutoText)
        self.answers_13.setScaledContents(True)
        self.answers_13.setObjectName("answers_13")
        self.gridLayout_2.addWidget(self.answers_13, 25, 4, 1, 1)
        self.answers_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_5.setEnabled(True)
        self.answers_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_5.setTextFormat(QtCore.Qt.AutoText)
        self.answers_5.setScaledContents(True)
        self.answers_5.setObjectName("answers_5")
        self.gridLayout_2.addWidget(self.answers_5, 9, 4, 1, 1)
        self.title_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_14.setScaledContents(True)
        self.title_14.setWordWrap(True)
        self.title_14.setObjectName("title_14")
        self.gridLayout_2.addWidget(self.title_14, 27, 0, 1, 1)
        self.describtion_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_15.setObjectName("describtion_15")
        self.gridLayout_2.addWidget(self.describtion_15, 29, 5, 1, 1)
        self.views_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_4.setScaledContents(True)
        self.views_4.setWordWrap(True)
        self.views_4.setObjectName("views_4")
        self.gridLayout_2.addWidget(self.views_4, 9, 3, 1, 1)
        self.views_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_12.setScaledContents(True)
        self.views_12.setWordWrap(True)
        self.views_12.setObjectName("views_12")
        self.gridLayout_2.addWidget(self.views_12, 23, 3, 1, 1)
        self.author_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_6.setWordWrap(True)
        self.author_6.setObjectName("author_6")
        self.gridLayout_2.addWidget(self.author_6, 11, 1, 1, 1)
        self.views_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_19.setScaledContents(True)
        self.views_19.setWordWrap(True)
        self.views_19.setObjectName("views_19")
        self.gridLayout_2.addWidget(self.views_19, 37, 3, 1, 1)
        self.answers_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_14.setEnabled(True)
        self.answers_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_14.setTextFormat(QtCore.Qt.AutoText)
        self.answers_14.setScaledContents(True)
        self.answers_14.setObjectName("answers_14")
        self.gridLayout_2.addWidget(self.answers_14, 27, 4, 1, 1)
        self.hour_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_10.setScaledContents(True)
        self.hour_10.setWordWrap(True)
        self.hour_10.setObjectName("hour_10")
        self.gridLayout_2.addWidget(self.hour_10, 19, 2, 1, 1)
        self.answers_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_16.setEnabled(True)
        self.answers_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_16.setTextFormat(QtCore.Qt.AutoText)
        self.answers_16.setScaledContents(True)
        self.answers_16.setObjectName("answers_16")
        self.gridLayout_2.addWidget(self.answers_16, 31, 4, 1, 1)
        self.describtion_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_18.setObjectName("describtion_18")
        self.gridLayout_2.addWidget(self.describtion_18, 35, 5, 1, 1)
        self.author_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_8.setWordWrap(True)
        self.author_8.setObjectName("author_8")
        self.gridLayout_2.addWidget(self.author_8, 15, 1, 1, 1)
        self.answers_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_6.setEnabled(True)
        self.answers_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_6.setTextFormat(QtCore.Qt.AutoText)
        self.answers_6.setScaledContents(True)
        self.answers_6.setObjectName("answers_6")
        self.gridLayout_2.addWidget(self.answers_6, 11, 4, 1, 1)
        self.hour_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_9.setScaledContents(True)
        self.hour_9.setWordWrap(True)
        self.hour_9.setObjectName("hour_9")
        self.gridLayout_2.addWidget(self.hour_9, 17, 2, 1, 1)
        self.views_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_6.setScaledContents(True)
        self.views_6.setWordWrap(True)
        self.views_6.setObjectName("views_6")
        self.gridLayout_2.addWidget(self.views_6, 11, 3, 1, 1)
        self.answers_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_10.setEnabled(True)
        self.answers_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_10.setTextFormat(QtCore.Qt.AutoText)
        self.answers_10.setScaledContents(True)
        self.answers_10.setObjectName("answers_10")
        self.gridLayout_2.addWidget(self.answers_10, 19, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 6, 0, 1, 6)
        self.describtion_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_1.setObjectName("describtion_1")
        self.gridLayout_2.addWidget(self.describtion_1, 1, 5, 1, 1)
        self.hour_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_1.setEnabled(True)
        self.hour_1.setTextFormat(QtCore.Qt.AutoText)
        self.hour_1.setScaledContents(True)
        self.hour_1.setWordWrap(True)
        self.hour_1.setObjectName("hour_1")
        self.gridLayout_2.addWidget(self.hour_1, 1, 2, 1, 1)
        self.hour_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_18.setScaledContents(True)
        self.hour_18.setWordWrap(True)
        self.hour_18.setObjectName("hour_18")
        self.gridLayout_2.addWidget(self.hour_18, 35, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 12, 0, 1, 6)
        self.answers_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_2.setEnabled(True)
        self.answers_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_2.setTextFormat(QtCore.Qt.AutoText)
        self.answers_2.setScaledContents(True)
        self.answers_2.setObjectName("answers_2")
        self.gridLayout_2.addWidget(self.answers_2, 3, 4, 1, 1)
        self.answers_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_20.setEnabled(True)
        self.answers_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_20.setTextFormat(QtCore.Qt.AutoText)
        self.answers_20.setScaledContents(True)
        self.answers_20.setObjectName("answers_20")
        self.gridLayout_2.addWidget(self.answers_20, 39, 4, 1, 1)
        self.hour_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_19.setScaledContents(True)
        self.hour_19.setWordWrap(True)
        self.hour_19.setObjectName("hour_19")
        self.gridLayout_2.addWidget(self.hour_19, 37, 2, 1, 1)
        self.title_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_15.setScaledContents(True)
        self.title_15.setWordWrap(True)
        self.title_15.setObjectName("title_15")
        self.gridLayout_2.addWidget(self.title_15, 29, 0, 1, 1)
        self.title_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_19.setScaledContents(True)
        self.title_19.setWordWrap(True)
        self.title_19.setObjectName("title_19")
        self.gridLayout_2.addWidget(self.title_19, 37, 0, 1, 1)
        self.answers_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_11.setEnabled(True)
        self.answers_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_11.setTextFormat(QtCore.Qt.AutoText)
        self.answers_11.setScaledContents(True)
        self.answers_11.setObjectName("answers_11")
        self.gridLayout_2.addWidget(self.answers_11, 21, 4, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_2.addWidget(self.line_14, 28, 0, 1, 6)
        self.describtion_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_17.setObjectName("describtion_17")
        self.gridLayout_2.addWidget(self.describtion_17, 33, 5, 1, 1)
        self.author_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_13.setWordWrap(True)
        self.author_13.setObjectName("author_13")
        self.gridLayout_2.addWidget(self.author_13, 25, 1, 1, 1)
        self.title_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_10.setScaledContents(True)
        self.title_10.setWordWrap(True)
        self.title_10.setObjectName("title_10")
        self.gridLayout_2.addWidget(self.title_10, 19, 0, 1, 1)
        self.author_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_4.setWordWrap(True)
        self.author_4.setObjectName("author_4")
        self.gridLayout_2.addWidget(self.author_4, 7, 1, 1, 1)
        self.title_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_2.setScaledContents(True)
        self.title_2.setWordWrap(True)
        self.title_2.setObjectName("title_2")
        self.gridLayout_2.addWidget(self.title_2, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 6)
        self.title_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_17.setScaledContents(True)
        self.title_17.setWordWrap(True)
        self.title_17.setObjectName("title_17")
        self.gridLayout_2.addWidget(self.title_17, 33, 0, 1, 1)
        self.describtion_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_13.setObjectName("describtion_13")
        self.gridLayout_2.addWidget(self.describtion_13, 25, 5, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 14, 0, 1, 6)
        self.title_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_20.setScaledContents(True)
        self.title_20.setWordWrap(True)
        self.title_20.setObjectName("title_20")
        self.gridLayout_2.addWidget(self.title_20, 39, 0, 1, 1)
        self.hour_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_15.setScaledContents(True)
        self.hour_15.setWordWrap(True)
        self.hour_15.setObjectName("hour_15")
        self.gridLayout_2.addWidget(self.hour_15, 29, 2, 1, 1)
        self.hour_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_16.setScaledContents(True)
        self.hour_16.setWordWrap(True)
        self.hour_16.setObjectName("hour_16")
        self.gridLayout_2.addWidget(self.hour_16, 31, 2, 1, 1)
        self.views_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_15.setScaledContents(True)
        self.views_15.setWordWrap(True)
        self.views_15.setObjectName("views_15")
        self.gridLayout_2.addWidget(self.views_15, 29, 3, 1, 1)
        self.hour_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_12.setScaledContents(True)
        self.hour_12.setWordWrap(True)
        self.hour_12.setObjectName("hour_12")
        self.gridLayout_2.addWidget(self.hour_12, 23, 2, 1, 1)
        self.views_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_18.setScaledContents(True)
        self.views_18.setWordWrap(True)
        self.views_18.setObjectName("views_18")
        self.gridLayout_2.addWidget(self.views_18, 35, 3, 1, 1)
        self.author_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_17.setWordWrap(True)
        self.author_17.setObjectName("author_17")
        self.gridLayout_2.addWidget(self.author_17, 33, 1, 1, 1)
        self.describtion_5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_5.setObjectName("describtion_5")
        self.gridLayout_2.addWidget(self.describtion_5, 9, 5, 1, 1)
        self.views_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_1.setScaledContents(True)
        self.views_1.setWordWrap(True)
        self.views_1.setObjectName("views_1")
        self.gridLayout_2.addWidget(self.views_1, 1, 3, 1, 1)
        self.views_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_5.setScaledContents(True)
        self.views_5.setWordWrap(True)
        self.views_5.setObjectName("views_5")
        self.gridLayout_2.addWidget(self.views_5, 7, 3, 1, 1)
        self.answers_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_1.setEnabled(True)
        self.answers_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_1.setTextFormat(QtCore.Qt.AutoText)
        self.answers_1.setScaledContents(True)
        self.answers_1.setObjectName("answers_1")
        self.gridLayout_2.addWidget(self.answers_1, 1, 4, 1, 1)
        self.answers_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_7.setEnabled(True)
        self.answers_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_7.setTextFormat(QtCore.Qt.AutoText)
        self.answers_7.setScaledContents(True)
        self.answers_7.setObjectName("answers_7")
        self.gridLayout_2.addWidget(self.answers_7, 13, 4, 1, 1)
        self.views_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_7.setScaledContents(True)
        self.views_7.setWordWrap(True)
        self.views_7.setObjectName("views_7")
        self.gridLayout_2.addWidget(self.views_7, 13, 3, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_2.addWidget(self.line_20, 40, 0, 1, 6)
        self.hour_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_3.setScaledContents(True)
        self.hour_3.setWordWrap(True)
        self.hour_3.setObjectName("hour_3")
        self.gridLayout_2.addWidget(self.hour_3, 5, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 22, 0, 1, 6)
        self.answers_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_12.setEnabled(True)
        self.answers_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_12.setTextFormat(QtCore.Qt.AutoText)
        self.answers_12.setScaledContents(True)
        self.answers_12.setObjectName("answers_12")
        self.gridLayout_2.addWidget(self.answers_12, 23, 4, 1, 1)
        self.views_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_11.setScaledContents(True)
        self.views_11.setWordWrap(True)
        self.views_11.setObjectName("views_11")
        self.gridLayout_2.addWidget(self.views_11, 21, 3, 1, 1)
        self.describtion_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_20.setObjectName("describtion_20")
        self.gridLayout_2.addWidget(self.describtion_20, 39, 5, 1, 1)
        self.describtion_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_3.setObjectName("describtion_3")
        self.gridLayout_2.addWidget(self.describtion_3, 5, 5, 1, 1)
        self.title_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_3.setScaledContents(True)
        self.title_3.setWordWrap(True)
        self.title_3.setObjectName("title_3")
        self.gridLayout_2.addWidget(self.title_3, 5, 0, 1, 1)
        self.title_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_8.setScaledContents(True)
        self.title_8.setWordWrap(True)
        self.title_8.setObjectName("title_8")
        self.gridLayout_2.addWidget(self.title_8, 15, 0, 1, 1)
        self.answers_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_17.setEnabled(True)
        self.answers_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_17.setTextFormat(QtCore.Qt.AutoText)
        self.answers_17.setScaledContents(True)
        self.answers_17.setObjectName("answers_17")
        self.gridLayout_2.addWidget(self.answers_17, 33, 4, 1, 1)
        self.describtion_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_10.setObjectName("describtion_10")
        self.gridLayout_2.addWidget(self.describtion_10, 19, 5, 1, 1)
        self.views_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_10.setScaledContents(True)
        self.views_10.setWordWrap(True)
        self.views_10.setObjectName("views_10")
        self.gridLayout_2.addWidget(self.views_10, 19, 3, 1, 1)
        self.hour_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_20.setScaledContents(True)
        self.hour_20.setWordWrap(True)
        self.hour_20.setObjectName("hour_20")
        self.gridLayout_2.addWidget(self.hour_20, 39, 2, 1, 1)
        self.views_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_9.setScaledContents(True)
        self.views_9.setWordWrap(True)
        self.views_9.setObjectName("views_9")
        self.gridLayout_2.addWidget(self.views_9, 17, 3, 1, 1)
        self.title_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_16.setScaledContents(True)
        self.title_16.setWordWrap(True)
        self.title_16.setObjectName("title_16")
        self.gridLayout_2.addWidget(self.title_16, 31, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 18, 0, 1, 6)
        self.hour_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_8.setScaledContents(True)
        self.hour_8.setWordWrap(True)
        self.hour_8.setObjectName("hour_8")
        self.gridLayout_2.addWidget(self.hour_8, 15, 2, 1, 1)
        self.describtion_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_6.setObjectName("describtion_6")
        self.gridLayout_2.addWidget(self.describtion_6, 11, 5, 1, 1)
        self.author_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_5.setWordWrap(True)
        self.author_5.setObjectName("author_5")
        self.gridLayout_2.addWidget(self.author_5, 9, 1, 1, 1)
        self.answers_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_4.setEnabled(True)
        self.answers_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_4.setTextFormat(QtCore.Qt.AutoText)
        self.answers_4.setScaledContents(True)
        self.answers_4.setObjectName("answers_4")
        self.gridLayout_2.addWidget(self.answers_4, 7, 4, 1, 1)
        self.title_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_12.setScaledContents(True)
        self.title_12.setWordWrap(True)
        self.title_12.setObjectName("title_12")
        self.gridLayout_2.addWidget(self.title_12, 23, 0, 1, 1)
        self.views_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.views_16.setScaledContents(True)
        self.views_16.setWordWrap(True)
        self.views_16.setObjectName("views_16")
        self.gridLayout_2.addWidget(self.views_16, 31, 3, 1, 1)
        self.hour_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_5.setScaledContents(True)
        self.hour_5.setWordWrap(True)
        self.hour_5.setObjectName("hour_5")
        self.gridLayout_2.addWidget(self.hour_5, 9, 2, 1, 1)
        self.answers_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_19.setEnabled(True)
        self.answers_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_19.setTextFormat(QtCore.Qt.AutoText)
        self.answers_19.setScaledContents(True)
        self.answers_19.setObjectName("answers_19")
        self.gridLayout_2.addWidget(self.answers_19, 37, 4, 1, 1)
        self.answers_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_15.setEnabled(True)
        self.answers_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_15.setTextFormat(QtCore.Qt.AutoText)
        self.answers_15.setScaledContents(True)
        self.answers_15.setObjectName("answers_15")
        self.gridLayout_2.addWidget(self.answers_15, 29, 4, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 24, 0, 1, 6)
        self.author_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_7.setWordWrap(True)
        self.author_7.setObjectName("author_7")
        self.gridLayout_2.addWidget(self.author_7, 13, 1, 1, 1)
        self.title_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_1.setScaledContents(False)
        self.title_1.setWordWrap(True)
        self.title_1.setObjectName("title_1")
        self.gridLayout_2.addWidget(self.title_1, 1, 0, 1, 1)
        self.describtion_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.describtion_7.setObjectName("describtion_7")
        self.gridLayout_2.addWidget(self.describtion_7, 13, 5, 1, 1)
        self.author_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_12.setWordWrap(True)
        self.author_12.setObjectName("author_12")
        self.gridLayout_2.addWidget(self.author_12, 23, 1, 1, 1)
        self.hour_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hour_14.setScaledContents(True)
        self.hour_14.setWordWrap(True)
        self.hour_14.setObjectName("hour_14")
        self.gridLayout_2.addWidget(self.hour_14, 27, 2, 1, 1)
        self.author_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.author_2.setWordWrap(True)
        self.author_2.setObjectName("author_2")
        self.gridLayout_2.addWidget(self.author_2, 3, 1, 1, 1)
        self.answers_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.answers_3.setEnabled(True)
        self.answers_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.answers_3.setTextFormat(QtCore.Qt.AutoText)
        self.answers_3.setScaledContents(True)
        self.answers_3.setObjectName("answers_3")
        self.gridLayout_2.addWidget(self.answers_3, 5, 4, 1, 1)
        self.title_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.title_9.setScaledContents(True)
        self.title_9.setWordWrap(True)
        self.title_9.setObjectName("title_9")
        self.gridLayout_2.addWidget(self.title_9, 17, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 4)
        self.update_progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.update_progress_bar.setProperty("value", 24)
        self.update_progress_bar.setObjectName("update_progress_bar")
        self.gridLayout.addWidget(self.update_progress_bar, 4, 1, 1, 1)
        self.notification_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.notification_check_box.setObjectName("notification_check_box")
        self.gridLayout.addWidget(self.notification_check_box, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.threadpool = QThreadPool()
        self.threadpool.setMaxThreadCount(10)
        print("Multithreading with maximum %d threads" % self.threadpool.maxThreadCount())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_main.setText(_translate("MainWindow", "TYTUŁ"))
        self.author_main.setText(_translate("MainWindow", "AUTOR"))
        self.hour_main.setText(_translate("MainWindow", "KIEDY DODANO"))
        self.views_main.setText(_translate("MainWindow", "ILOŚĆ WYŚWIETLEŃ"))
        self.answers_main.setText(_translate("MainWindow", "ILOŚĆ ODPOWIEDZI"))
        self.describtion_main.setText(_translate("MainWindow", "SZCZEGÓŁY"))
        self.last_update.setText(_translate("MainWindow", "LAST UPDATE: 26.04.2020 20:20:20"))
        self.describtion_4.setText(_translate("MainWindow", "Wyświetl opis"))
        self.title_7.setText(_translate("MainWindow", "Title_7"))
        self.describtion_9.setText(_translate("MainWindow", "Wyświetl opis"))
        self.title_5.setText(_translate("MainWindow", "Title_5"))
        self.author_14.setText(_translate("MainWindow", "Author_14"))
        self.author_19.setText(_translate("MainWindow", "Author_19"))
        self.title_18.setText(_translate("MainWindow", "Title_18"))
        self.describtion_12.setText(_translate("MainWindow", "Wyświetl opis"))
        self.answers_9.setText(_translate("MainWindow", "Answers_9"))
        self.describtion_14.setText(_translate("MainWindow", "Wyświetl opis"))
        self.title_13.setText(_translate("MainWindow", "Title_13"))
        self.author_3.setText(_translate("MainWindow", "Author_3"))
        self.hour_7.setText(_translate("MainWindow", "Hour_7"))
        self.answers_18.setText(_translate("MainWindow", "Answers_18"))
        self.hour_2.setText(_translate("MainWindow", "Hour_2"))
        self.title_4.setText(_translate("MainWindow", "Title_4"))
        self.hour_6.setText(_translate("MainWindow", "Hour_6"))
        self.describtion_2.setText(_translate("MainWindow", "Wyświetl opis"))
        self.views_13.setText(_translate("MainWindow", "Views_13"))
        self.author_11.setText(_translate("MainWindow", "Author_11"))
        self.views_20.setText(_translate("MainWindow", "Views_20"))
        self.views_17.setText(_translate("MainWindow", "Views_17"))
        self.title_6.setText(_translate("MainWindow", "Title_6"))
        self.hour_4.setText(_translate("MainWindow", "Hour_4"))
        self.author_20.setText(_translate("MainWindow", "Author_20"))
        self.author_9.setText(_translate("MainWindow", "Author_9"))
        self.views_14.setText(_translate("MainWindow", "Views_14"))
        self.describtion_16.setText(_translate("MainWindow", "Wyświetl opis"))
        self.author_16.setText(_translate("MainWindow", "Author_16"))
        self.hour_17.setText(_translate("MainWindow", "Hour_17"))
        self.answers_8.setText(_translate("MainWindow", "Answers_8"))
        self.author_1.setText(_translate("MainWindow", "Author_1"))
        self.views_8.setText(_translate("MainWindow", "Views_8"))
        self.author_10.setText(_translate("MainWindow", "Author_10"))
        self.describtion_11.setText(_translate("MainWindow", "Wyświetl opis"))
        self.describtion_19.setText(_translate("MainWindow", "Wyświetl opis"))
        self.hour_13.setText(_translate("MainWindow", "Hour_13"))
        self.author_18.setText(_translate("MainWindow", "Author_18"))
        self.title_11.setText(_translate("MainWindow", "Title_11"))
        self.views_2.setText(_translate("MainWindow", "Views_2"))
        self.hour_11.setText(_translate("MainWindow", "Hour_11"))
        self.views_3.setText(_translate("MainWindow", "Views_3"))
        self.author_15.setText(_translate("MainWindow", "Author_15"))
        self.describtion_8.setText(_translate("MainWindow", "Wyświetl opis"))
        self.answers_13.setText(_translate("MainWindow", "Answers_13"))
        self.answers_5.setText(_translate("MainWindow", "Answers_5"))
        self.title_14.setText(_translate("MainWindow", "Title_14"))
        self.describtion_15.setText(_translate("MainWindow", "Wyświetl opis"))
        self.views_4.setText(_translate("MainWindow", "Views_5"))
        self.views_12.setText(_translate("MainWindow", "Views_12"))
        self.author_6.setText(_translate("MainWindow", "Author_6"))
        self.views_19.setText(_translate("MainWindow", "Views_19"))
        self.answers_14.setText(_translate("MainWindow", "Answers_14"))
        self.hour_10.setText(_translate("MainWindow", "Hour_10"))
        self.answers_16.setText(_translate("MainWindow", "Answers_16"))
        self.describtion_18.setText(_translate("MainWindow", "Wyświetl opis"))
        self.author_8.setText(_translate("MainWindow", "Author_8"))
        self.answers_6.setText(_translate("MainWindow", "Answers_6"))
        self.hour_9.setText(_translate("MainWindow", "Hour_9"))
        self.views_6.setText(_translate("MainWindow", "Views_6"))
        self.answers_10.setText(_translate("MainWindow", "Answers_10"))
        self.describtion_1.setText(_translate("MainWindow", "Wyświetl opis"))
        self.hour_1.setText(_translate("MainWindow", "Hour_1"))
        self.hour_18.setText(_translate("MainWindow", "Hour_18"))
        self.answers_2.setText(_translate("MainWindow", "Answers_2"))
        self.answers_20.setText(_translate("MainWindow", "Answers_20"))
        self.hour_19.setText(_translate("MainWindow", "Hour_19"))
        self.title_15.setText(_translate("MainWindow", "Title_15"))
        self.title_19.setText(_translate("MainWindow", "Title_19"))
        self.answers_11.setText(_translate("MainWindow", "Answers_11"))
        self.describtion_17.setText(_translate("MainWindow", "Wyświetl opis"))
        self.author_13.setText(_translate("MainWindow", "Author_13"))
        self.title_10.setText(_translate("MainWindow", "Title_10"))
        self.author_4.setText(_translate("MainWindow", "Author_4"))
        self.title_2.setText(_translate("MainWindow", "Title_2"))
        self.title_17.setText(_translate("MainWindow", "Title_17"))
        self.describtion_13.setText(_translate("MainWindow", "Wyświetl opis"))
        self.title_20.setText(_translate("MainWindow", "Title_20"))
        self.hour_15.setText(_translate("MainWindow", "Hour_15"))
        self.hour_16.setText(_translate("MainWindow", "Hour_16"))
        self.views_15.setText(_translate("MainWindow", "Views_15"))
        self.hour_12.setText(_translate("MainWindow", "Hour_12"))
        self.views_18.setText(_translate("MainWindow", "Views_18"))
        self.author_17.setText(_translate("MainWindow", "Author_17"))
        self.describtion_5.setText(_translate("MainWindow", "Wyświetl opis"))
        self.views_1.setText(_translate("MainWindow", "Views_1"))
        self.views_5.setText(_translate("MainWindow", "Views_4"))
        self.answers_1.setText(_translate("MainWindow", "Answers_1"))
        self.answers_7.setText(_translate("MainWindow", "Answers_7"))
        self.views_7.setText(_translate("MainWindow", "Views_7"))
        self.hour_3.setText(_translate("MainWindow", "Hour_3"))
        self.answers_12.setText(_translate("MainWindow", "Answers_12"))
        self.views_11.setText(_translate("MainWindow", "Views_11"))
        self.describtion_20.setText(_translate("MainWindow", "Wyświetl opis"))
        self.describtion_3.setText(_translate("MainWindow", "Wyświetl opis"))
        self.title_3.setText(_translate("MainWindow", "Title_3"))
        self.title_8.setText(_translate("MainWindow", "Title_8"))
        self.answers_17.setText(_translate("MainWindow", "Answers_17"))
        self.describtion_10.setText(_translate("MainWindow", "Wyświetl opis"))
        self.views_10.setText(_translate("MainWindow", "Views_10"))
        self.hour_20.setText(_translate("MainWindow", "Hour_20"))
        self.views_9.setText(_translate("MainWindow", "Views_9"))
        self.title_16.setText(_translate("MainWindow", "Title_16"))
        self.hour_8.setText(_translate("MainWindow", "Hour_8"))
        self.describtion_6.setText(_translate("MainWindow", "Wyświetl opis"))
        self.author_5.setText(_translate("MainWindow", "Author_5"))
        self.answers_4.setText(_translate("MainWindow", "Answers_4"))
        self.title_12.setText(_translate("MainWindow", "Title_12"))
        self.views_16.setText(_translate("MainWindow", "Views_16"))
        self.hour_5.setText(_translate("MainWindow", "Hour_5"))
        self.answers_19.setText(_translate("MainWindow", "Answers_19"))
        self.answers_15.setText(_translate("MainWindow", "Answers_15"))
        self.author_7.setText(_translate("MainWindow", "Author_7"))
        self.title_1.setText(_translate("MainWindow", "Title_1"))
        self.describtion_7.setText(_translate("MainWindow", "Wyświetl opis"))
        self.author_12.setText(_translate("MainWindow", "Author_12"))
        self.hour_14.setText(_translate("MainWindow", "Hour_14"))
        self.author_2.setText(_translate("MainWindow", "Author_2"))
        self.answers_3.setText(_translate("MainWindow", "Answers_3"))
        self.title_9.setText(_translate("MainWindow", "Title_9"))
        self.notification_check_box.setText(_translate("MainWindow", "Powiadomienia włączone"))

    def update(self):
        print("UPDATE STARTED")
        # self.label_1.setText(main_list.return_author_data(0))
        # self.label_2.setText(main_list.return_time_data(0))
        # self.label_3.setText(main_list.return_title_data(0))
        # # self.label_4.setText(main_list.return_describtion_data(0))
        # self.label_5.setText(main_list.return_views_data(0))
        # self.label_6.setText(main_list.return_answears_data(0))
        #
        # self.label_7.setText(main_list.return_author_data(1))
        # self.label_8.setText(main_list.return_time_data(1))
        # self.label_9.setText(main_list.return_title_data(1))
        # # self.label_10.setText(main_list.return_describtion_data(1))
        # self.label_11.setText(main_list.return_views_data(1))
        # self.label_12.setText(main_list.return_answears_data(1))
        #
        # self.label_13.setText(main_list.return_author_data(2))
        # self.label_14.setText(main_list.return_time_data(2))
        # self.label_15.setText(main_list.return_title_data(2))
        # # self.label_16.setText(main_list.return_describtion_data(2))
        # self.label_17.setText(main_list.return_views_data(2))
        # self.label_18.setText(main_list.return_answears_data(2))
        #
        # self.label_19.setText(main_list.return_author_data(3))
        # self.label_20.setText(main_list.return_time_data(3))
        # self.label_21.setText(main_list.return_title_data(3))
        # # self.label_22.setText(main_list.return_describtion_data(3))
        # self.label_23.setText(main_list.return_views_data(3))
        # self.label_24.setText(main_list.return_answears_data(3))
        #
        # self.label_25.setText(main_list.return_author_data(4))
        # self.label_26.setText(main_list.return_time_data(4))
        # self.label_27.setText(main_list.return_title_data(4))
        # # self.label_28.setText(main_list.return_describtion_data(4))
        # self.label_29.setText(main_list.return_views_data(4))
        # self.label_30.setText(main_list.return_answears_data(4))
        #
        # self.label_31.setText(main_list.return_author_data(5))
        # self.label_32.setText(main_list.return_time_data(5))
        # self.label_33.setText(main_list.return_title_data(5))
        # # self.label_34.setText(main_list.return_describtion_data(5))
        # self.label_35.setText(main_list.return_views_data(5))
        # self.label_36.setText(main_list.return_answears_data(5))
        #
        # self.label_37.setText(main_list.return_author_data(6))
        # self.label_38.setText(main_list.return_time_data(6))
        # self.label_39.setText(main_list.return_title_data(6))
        # # self.label_40.setText(main_list.return_describtion_data(6))
        # self.label_41.setText(main_list.return_views_data(6))
        # self.label_42.setText(main_list.return_answears_data(6))
        #
        # self.label_43.setText(main_list.return_author_data(7))
        # self.label_44.setText(main_list.return_time_data(7))
        # self.label_45.setText(main_list.return_title_data(7))
        # # self.label_46.setText(main_list.return_describtion_data(7))
        # self.label_47.setText(main_list.return_views_data(7))
        # self.label_48.setText(main_list.return_answears_data(7))

        print("UPDATE ENDED")

    def timer(self):
        while True:
            time.sleep(60)
            worker = Worker(self.update)
            self.threadpool.start(worker)



    def new_thread_update(self):
        worker = Worker(self.timer)
        self.threadpool.start(worker)





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()


    sys.exit(app.exec_())


