# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *

import list_of_post as list
import time

class Worker(QRunnable):
    '''
    Worker thread

    Inherits from QRunnable to handler worker thread setup, signals and wrap-up.

    :param callback: The function callback to run on this worker thread. Supplied args and
                     kwargs will be passed through to the runner.
    :type callback: function
    :param args: Arguments to pass to the callback function
    :param kwargs: Keywords to pass to the callback function

    '''

    def __init__(self, fn, *args, **kwargs):
        super(Worker, self).__init__()
        # Store constructor arguments (re-used for processing)
        self.fn = fn
        self.args = args
        self.kwargs = kwargs

    def run(self):
        '''
        Initialise the runner function with passed args, kwargs.
        '''
        self.fn(*self.args, **self.kwargs)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(954, 684)

        self.threadpool = QThreadPool()
        self.threadpool.setMaxThreadCount(10)
        print("Multithreading with maximum %d threads" % self.threadpool.maxThreadCount())

        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 934, 644))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 8, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 8, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 8, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 6, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 6, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 1, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 10, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 7, 8, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 7, 4, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 6, 10, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 6, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 5, 10, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 6, 8, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 10, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 7, 6, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 1, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 6, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 5, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 3, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 8, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 7, 10, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 6, 4, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 1, 10, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 0, 9, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setWordWrap(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 5, 8, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_1.setWordWrap(True)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 5, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 10, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 7, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 4, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 6, 6, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 5, 6, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 8, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 8, 4, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 8, 6, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 8, 8, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 8, 10, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label_11.setText(_translate("mainWindow", "TextLabel"))
        self.label_43.setText(_translate("mainWindow", "TextLabel"))
        self.label_23.setText(_translate("mainWindow", "TextLabel"))
        self.label_32.setText(_translate("mainWindow", "TextLabel"))
        self.label_31.setText(_translate("mainWindow", "TextLabel"))
        self.label_12.setText(_translate("mainWindow", "TextLabel"))
        self.label_41.setText(_translate("mainWindow", "TextLabel"))
        self.label_39.setText(_translate("mainWindow", "TextLabel"))
        self.label_36.setText(_translate("mainWindow", "TextLabel"))
        self.label_37.setText(_translate("mainWindow", "TextLabel"))
        self.label_4.setText(_translate("mainWindow", "TextLabel"))
        self.label_22.setText(_translate("mainWindow", "TextLabel"))
        self.label_13.setText(_translate("mainWindow", "TextLabel"))
        self.label_30.setText(_translate("mainWindow", "TextLabel"))
        self.label_35.setText(_translate("mainWindow", "TextLabel"))
        self.label_3.setText(_translate("mainWindow", "TextLabel"))
        self.label_6.setText(_translate("mainWindow", "TextLabel"))
        self.label_25.setText(_translate("mainWindow", "TextLabel"))
        self.label_8.setText(_translate("mainWindow", "TextLabel"))
        self.label_40.setText(_translate("mainWindow", "TextLabel"))
        self.label_16.setText(_translate("mainWindow", "TextLabel"))
        self.label_26.setText(_translate("mainWindow", "TextLabel"))
        self.label_20.setText(_translate("mainWindow", "TextLabel"))
        self.label_7.setText(_translate("mainWindow", "TextLabel"))
        self.label_2.setText(_translate("mainWindow", "TextLabel"))
        self.label_19.setText(_translate("mainWindow", "TextLabel"))
        self.label_18.setText(_translate("mainWindow", "TextLabel"))
        self.label_14.setText(_translate("mainWindow", "TextLabel"))
        self.label_17.setText(_translate("mainWindow", "TextLabel"))
        self.label_15.setText(_translate("mainWindow", "TextLabel"))
        self.label_42.setText(_translate("mainWindow", "TextLabel"))
        self.label_33.setText(_translate("mainWindow", "TextLabel"))
        self.label_29.setText(_translate("mainWindow", "TextLabel"))
        self.label_1.setText(_translate("mainWindow", "TextLabel"))
        self.label_27.setText(_translate("mainWindow", "TextLabel"))
        self.label_24.setText(_translate("mainWindow", "TextLabel"))
        self.label_21.setText(_translate("mainWindow", "TextLabel"))
        self.label_38.setText(_translate("mainWindow", "TextLabel"))
        self.label_5.setText(_translate("mainWindow", "TextLabel"))
        self.label_10.setText(_translate("mainWindow", "TextLabel"))
        self.label_9.setText(_translate("mainWindow", "TextLabel"))
        self.label_34.setText(_translate("mainWindow", "TextLabel"))
        self.label_28.setText(_translate("mainWindow", "TextLabel"))
        self.label_44.setText(_translate("mainWindow", "TextLabel"))
        self.label_45.setText(_translate("mainWindow", "TextLabel"))
        self.label_46.setText(_translate("mainWindow", "TextLabel"))
        self.label_47.setText(_translate("mainWindow", "TextLabel"))
        self.label_48.setText(_translate("mainWindow", "TextLabel"))

    def update(self):
        print("UPDATE STARTED")
        self.label_1.setText(main_list.return_author_data(0))
        self.label_2.setText(main_list.return_time_data(0))
        self.label_3.setText(main_list.return_title_data(0))
        # self.label_4.setText(main_list.return_describtion_data(0))
        self.label_5.setText(main_list.return_views_data(0))
        self.label_6.setText(main_list.return_answears_data(0))

        self.label_7.setText(main_list.return_author_data(1))
        self.label_8.setText(main_list.return_time_data(1))
        self.label_9.setText(main_list.return_title_data(1))
        # self.label_10.setText(main_list.return_describtion_data(1))
        self.label_11.setText(main_list.return_views_data(1))
        self.label_12.setText(main_list.return_answears_data(1))

        self.label_13.setText(main_list.return_author_data(2))
        self.label_14.setText(main_list.return_time_data(2))
        self.label_15.setText(main_list.return_title_data(2))
        # self.label_16.setText(main_list.return_describtion_data(2))
        self.label_17.setText(main_list.return_views_data(2))
        self.label_18.setText(main_list.return_answears_data(2))

        self.label_19.setText(main_list.return_author_data(3))
        self.label_20.setText(main_list.return_time_data(3))
        self.label_21.setText(main_list.return_title_data(3))
        # self.label_22.setText(main_list.return_describtion_data(3))
        self.label_23.setText(main_list.return_views_data(3))
        self.label_24.setText(main_list.return_answears_data(3))

        self.label_25.setText(main_list.return_author_data(4))
        self.label_26.setText(main_list.return_time_data(4))
        self.label_27.setText(main_list.return_title_data(4))
        # self.label_28.setText(main_list.return_describtion_data(4))
        self.label_29.setText(main_list.return_views_data(4))
        self.label_30.setText(main_list.return_answears_data(4))

        self.label_31.setText(main_list.return_author_data(5))
        self.label_32.setText(main_list.return_time_data(5))
        self.label_33.setText(main_list.return_title_data(5))
        # self.label_34.setText(main_list.return_describtion_data(5))
        self.label_35.setText(main_list.return_views_data(5))
        self.label_36.setText(main_list.return_answears_data(5))

        self.label_37.setText(main_list.return_author_data(6))
        self.label_38.setText(main_list.return_time_data(6))
        self.label_39.setText(main_list.return_title_data(6))
        # self.label_40.setText(main_list.return_describtion_data(6))
        self.label_41.setText(main_list.return_views_data(6))
        self.label_42.setText(main_list.return_answears_data(6))

        self.label_43.setText(main_list.return_author_data(7))
        self.label_44.setText(main_list.return_time_data(7))
        self.label_45.setText(main_list.return_title_data(7))
        # self.label_46.setText(main_list.return_describtion_data(7))
        self.label_47.setText(main_list.return_views_data(7))
        self.label_48.setText(main_list.return_answears_data(7))

        print("UPDATE ENDED")

    def timer(self):
        while True:
            time.sleep(60)
            worker = Worker(self.update)
            self.threadpool.start(worker)



    def new_thread_update(self):
        worker = Worker(self.timer)
        self.threadpool.start(worker)








if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    main_list = list.List_of_posts()
    ui.new_thread_update()
    sys.exit(app.exec_())
